### ISSUE TITLE
medspace UI6

### ISSUE THREAD

**Issue by Aryasatheesan** [vasudevareddyreddem/medspace#7]
![image](https://user-images.githubusercontent.com/39790889/41638267-257de458-7476-11e8-8ce8-0f734b20c4c5.png)

start sentences from the begining
role->admin->BMW vehicle->Add BMW vehicle/add HCF/add CBWTF
http://medspace.cloudkoza.com/garbage/add
http://medspace.cloudkoza.com/hospital/add
edspace.cloudkoza.com/plant/add

**Comment by bayapucg** [comment]
as for discussion is fine
